(SELECT CITY, CHAR_LENGTH(CITY) AS 'length'
FROM STATION 
ORDER BY length DESC, CITY ASC 
LIMIT 1)

UNION

(SELECT CITY, CHAR_LENGTH(CITY) AS 'length'
FROM STATION 
ORDER BY length ASC, CITY ASC 
LIMIT 1);